# Generated by Django 4.2.3 on 2023-07-24 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccounts',
            fields=[
                ('from_email_account_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_email_account_id_status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('DELETED', 'DELETED')], default='INACTIVE', max_length=10)),
                ('from_email', models.EmailField(max_length=254)),
                ('from_password', models.CharField(max_length=100)),
                ('from_imap_address', models.CharField(max_length=200)),
                ('from_imap_port', models.PositiveIntegerField()),
                ('from_smtp_address', models.CharField(max_length=200)),
                ('from_smtp_port', models.PositiveIntegerField()),
                ('from_warmup_emails_sent', models.PositiveIntegerField()),
                ('sagemode_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
