# Generated by Django 4.2.3 on 2023-10-07 15:14

import dashboard.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccounts',
            fields=[
                ('from_email_account_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_email_account_id_status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('DELETED', 'DELETED')], default='INACTIVE', max_length=10)),
                ('from_email', models.EmailField(max_length=254, unique=True)),
                ('from_password', models.CharField(max_length=100)),
                ('from_imap_address', models.CharField(max_length=200)),
                ('from_imap_port', models.PositiveIntegerField()),
                ('from_smtp_address', models.CharField(max_length=200)),
                ('from_smtp_port', models.PositiveIntegerField()),
                ('from_warmup_emails_sent_per_week', models.PositiveIntegerField(default=0)),
                ('from_warmup_emails_to_be_sent_today', models.PositiveIntegerField(default=0)),
                ('from_warmup_email_to_be_sent_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('sagemode_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Campaigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('campaign_name', models.CharField(max_length=100)),
                ('campaign_active', models.BooleanField(default=True)),
                ('sending_time', models.TimeField(default=dashboard.models.current_time)),
                ('composed_text', models.CharField(max_length=2000)),
                ('sagemode_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignEmails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('email_active', models.BooleanField(default=True)),
                ('campaign_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.campaigns')),
            ],
        ),
    ]
