# Generated by Django 4.2.3 on 2023-10-12 07:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Campaigns',
            new_name='Campaign',
        ),
        migrations.RenameModel(
            old_name='CampaignEmails',
            new_name='CampaignEmail',
        ),
        migrations.RenameModel(
            old_name='EmailAccounts',
            new_name='EmailAccount',
        ),
    ]
