# Generated by Django 4.2.3 on 2023-08-13 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_emailaccounts_from_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccounts',
            name='from_warmup_email_to_be_sent_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 13, 22, 21, 51, 105712)),
        ),
        migrations.AddField(
            model_name='emailaccounts',
            name='from_warmup_emails_to_be_sent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
