# Generated by Django 4.2.3 on 2023-08-13 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_emailaccounts_from_warmup_email_to_be_sent_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailaccounts',
            old_name='from_warmup_emails_sent',
            new_name='from_warmup_emails_sent_per_week',
        ),
        migrations.RenameField(
            model_name='emailaccounts',
            old_name='from_warmup_emails_to_be_sent',
            new_name='from_warmup_emails_to_be_sent_today',
        ),
        migrations.AlterField(
            model_name='emailaccounts',
            name='from_warmup_email_to_be_sent_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 13, 22, 24, 37, 856868)),
        ),
    ]
