# Generated by Django 4.2.3 on 2023-09-12 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_from_warmup_emails_sent_emailaccounts_from_warmup_emails_sent_per_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaccounts',
            name='from_warmup_email_to_be_sent_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 12, 11, 56, 57, 873706)),
        ),
    ]
